// AUTO-GENERATED by @vue-godot/cli — do not edit manually
/// <reference types="vite/client" />

declare module '*.vue' {
  import type { DefineComponent } from '@vue/runtime-core'
  const component: DefineComponent<
    Record<string, unknown>,
    Record<string, unknown>,
    Record<string, unknown>
  >
  export default component
}
