// Generated by scripts/generate-types.mjs. Do not edit.
// Godot Engine v4.4.1.stable.official; extension_api.json sha256 1136ad8c676034a0d9ac15ec55f1f4c79f300fd645f45a08a129c0254ca95d51.
// Compatibility is intentionally limited to the migration surface below.

declare module 'godot-jsb' {
  import type { Callable, GodotVariant, Object, PackedByteArray } from 'godot'

  /** @deprecated Prefer Callable.create(). */
  export function callable<Arguments extends readonly unknown[], Result>(
    callback: (...args: Arguments) => Result,
  ): Callable<Arguments, Result>
  /** @deprecated Prefer Callable.create(). */
  export function callable<Arguments extends readonly unknown[], Result>(
    target: Object | GodotVariant,
    callback: (...args: Arguments) => Result,
  ): Callable<Arguments, Result>
  /** @deprecated Prefer PackedByteArray.to_array_buffer(). */
  export function to_array_buffer(packed: PackedByteArray): ArrayBuffer
  export const version: string
  export const impl: 'QuickJS-ng'
}
