// Generated by scripts/generate-types.mjs. Do not edit.
// Godot Engine v4.4.1.stable.official; extension_api.json sha256 1136ad8c676034a0d9ac15ec55f1f4c79f300fd645f45a08a129c0254ca95d51.

declare module 'godot-js' {
  export type RuntimeFeature =
    | 'commonjs'
    | 'esm'
    | 'godot-binding'
    | 'godot-variant-bridge'
    | 'json-modules'
    | 'promise-jobs'
    | 'quickjs-ng'
    | 'resource-modules'
    | 'source-maps'

  export type GodotScriptClass<Instance extends object = object> = abstract new (
    ...args: never[]
  ) => Instance

  export interface ScriptPropertyMetadata {
    readonly type: string
    readonly default?: unknown
    readonly hint?: Readonly<Record<string, unknown>>
  }

  export interface ScriptSignalArgument {
    readonly name: string
    readonly type: string
  }

  export interface ScriptMetadata {
    readonly properties?: Readonly<Record<string, ScriptPropertyMetadata>>
    readonly signals?: Readonly<Record<string, readonly ScriptSignalArgument[]>>
    readonly tool?: boolean
    readonly rpc?: Readonly<Record<string, Readonly<Record<string, unknown>>>>
  }

  export type DefinedScript<ScriptClass extends GodotScriptClass> = ScriptClass & {
    readonly [key: symbol]: Readonly<ScriptMetadata>
  }

  export function runtimeVersion(): string
  export function quickJSVersion(): string
  export function runtimeFeatures(): RuntimeFeature[]
  export function hasFeature(feature: RuntimeFeature | string): boolean
  export function collectGarbage(): void
  export function defineScript<ScriptClass extends GodotScriptClass>(
    scriptClass: ScriptClass,
    metadata: ScriptMetadata,
  ): DefinedScript<ScriptClass>
  export function getScriptMetadata(
    value: unknown,
  ): Readonly<ScriptMetadata> | undefined
}
