import * as fs from 'node:fs'
import * as path from 'node:path'

export { diagnoseProject, printDoctorReport, runDoctor } from './doctor.js'
export type {
  DoctorCheck,
  DoctorOptions,
  DoctorOutput,
  DoctorReport,
  DoctorStatus,
} from './doctor.js'

export interface GenerateOptions {
  /** Directory containing godot*.gen.d.ts files */
  typingsDir: string
  /** Output file path for the generated .d.ts */
  outFile: string
  /**
   * Base class name to filter by inheritance.
   * Only classes derived from this ancestor will be included.
   * @default 'Control'
   */
  ancestor?: string
  /**
   * Directory containing Vue source files (e.g. `vue/src`).
   * When set, an `env.d.ts` shim will be generated there.
   */
  vueSrcDir?: string
}

/**
 * Parse all `class Foo<…> extends Bar<…>` declarations from godot*.gen.d.ts
 * and build a { className → parentClassName } map.
 */
function parseClassHierarchy(typingsDir: string): Map<string, string> {
  const classes = new Map<string, string>()
  const files = fs
    .readdirSync(typingsDir)
    .filter((f) => /^godot\d*\.gen\.d\.ts$/.test(f) || f === 'godot.mix.d.ts')

  for (const file of files.sort()) {
    const content = fs.readFileSync(path.join(typingsDir, file), 'utf-8')
    const re = /class\s+(\w+)\s*<.*?>\s+extends\s+(\w+)/g
    let m: RegExpExecArray | null
    while ((m = re.exec(content)) !== null) {
      classes.set(m[1], m[2])
    }
  }

  return classes
}

/**
 * Walk the inheritance chain of `cls` and return all ancestor class names.
 */
function getAncestors(cls: string, classes: Map<string, string>): string[] {
  const chain: string[] = []
  const visited = new Set<string>()
  let current = cls
  while (classes.has(current) && !visited.has(current)) {
    visited.add(current)
    const parent = classes.get(current)!
    chain.push(parent)
    current = parent
  }
  return chain
}

/**
 * Return all class names that inherit (directly or transitively) from `ancestor`,
 * plus the ancestor itself.
 */
function getDescendants(
  classes: Map<string, string>,
  ancestor: string,
): string[] {
  const result: string[] = []
  for (const cls of classes.keys()) {
    if (cls === ancestor || getAncestors(cls, classes).includes(ancestor)) {
      result.push(cls)
    }
  }
  return result.sort()
}

/**
 * Generate the `declare module "@vue/runtime-core"` augmentation source text.
 */
export function generateSource(options: GenerateOptions): string {
  const { typingsDir, ancestor = 'Control' } = options
  const classes = parseClassHierarchy(typingsDir)
  const nodes = getDescendants(classes, ancestor)

  const lines: string[] = [
    '// AUTO-GENERATED by @vue-godot/cli — do not edit manually',
    '// Augments @vue/runtime-core GlobalComponents so Volar provides',
    '// typed props when using Godot nodes in Vue templates.',
    '',
    'import type { AllowedComponentProps, VNodeProps } from "@vue/runtime-core"',
    '',
    '/**',
    ' * Extracts settable (non-method) instance properties from a Godot node class.',
    ' * All keys become optional since props are optional in Vue templates.',
    ' */',
    'type GodotMethod = (...args: never[]) => unknown',
    '',
    'type GodotProps<T> = {',
    '  [K in keyof T as T[K] extends GodotMethod ? never : K]?: T[K]',
    '}',
    '',
    'type VueGodotComponentProps<T> = GodotProps<T> & AllowedComponentProps & VNodeProps',
    '',
    'declare module "@vue/runtime-core" {',
    '  interface GlobalComponents {',
  ]

  for (const node of nodes) {
    lines.push(
      `    ${node}: new () => { $props: VueGodotComponentProps<import("godot").${node}> }`,
    )
  }

  lines.push('  }', '}', '', 'declare module "vue" {', '  export interface GlobalComponents {')

  for (const node of nodes) {
    lines.push(
      `    ${node}: new () => { $props: VueGodotComponentProps<import("godot").${node}> }`,
    )
  }

  lines.push('  }', '}', '')
  return lines.join('\n')
}

/**
 * Generate the Vue env.d.ts shim source text.
 */
export function generateEnvDtsSource(): string {
  return [
    '// AUTO-GENERATED by @vue-godot/cli — do not edit manually',
    '/// <reference types="vite/client" />',
    '',
    "declare module '*.vue' {",
    "  import type { DefineComponent } from '@vue/runtime-core'",
    '  const component: DefineComponent<',
    '    Record<string, unknown>,',
    '    Record<string, unknown>,',
    '    Record<string, unknown>',
    '  >',
    '  export default component',
    '}',
    '',
  ].join('\n')
}

/**
 * Generate and write the augmentation file (and optionally env.d.ts).
 */
export function generate(options: GenerateOptions): void {
  const source = generateSource(options)
  const outDir = path.dirname(options.outFile)
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true })
  }
  fs.writeFileSync(options.outFile, source, 'utf-8')

  // Count unique components (the source augments both "@vue/runtime-core" and "vue")
  const count = new Set(
    source
      .split('\n')
      .map((l) => l.match(/^\s{4}(\w+):/))
      .filter((m): m is RegExpMatchArray => m !== null)
      .map((m) => m[1]),
  ).size

  console.log(
    `@vue-godot/cli: wrote ${count} ${options.ancestor ?? 'Control'}-derived component types → ${options.outFile}`,
  )

  // Generate env.d.ts shim for Vue SFC support
  if (options.vueSrcDir) {
    const envFile = path.join(options.vueSrcDir, 'env.d.ts')
    if (!fs.existsSync(options.vueSrcDir)) {
      fs.mkdirSync(options.vueSrcDir, { recursive: true })
    }
    fs.writeFileSync(envFile, generateEnvDtsSource(), 'utf-8')
    console.log(`@vue-godot/cli: wrote env.d.ts → ${envFile}`)
  }
}
